<a href="https://colab.research.google.com/github/srinivas340/ml_practice/blob/main/handling_imalance_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Imbalanced dataset:

A dataset with an unequal class distribution

In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('/content/credit_data.csv')

In [3]:
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [4]:
df.shape

(91200, 31)

In [5]:
df['Class'].value_counts()

Class
0.0    90988
1.0      211
Name: count, dtype: int64

0-->Legt Transactions

1-->Fraudulent Transaction

In [6]:
legit=df[df.Class==0]
fraud=df[df.Class==1]

In [7]:
print(legit.shape)
print(fraud.shape)

(90988, 31)
(211, 31)

Under sampling

Build a sample dataset containing similar distribution of legit & fraudulent transactions

In [8]:
legit_sample=legit.sample(n=211)

In [9]:
legit_sample.shape

(211, 31)

Concatenate the two dataframe

In [11]:
new_df=pd.concat([legit_sample,fraud],axis=0)

In [12]:
new_df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
42917,41296,1.368765,-1.361186,0.626250,-1.456510,-1.736567,-0.286272,-1.331124,0.048931,-1.743443,...,-0.003391,0.210624,-0.095507,-0.006571,0.311970,-0.104763,0.032745,0.022377,69.00,0.0
50749,44631,-1.411487,0.372310,1.628897,1.325167,-0.295508,0.249102,-0.238239,0.590134,0.043948,...,0.133816,0.518698,-0.345721,0.147957,-0.014004,-0.204995,0.043104,-0.089298,54.83,0.0
63993,50971,1.134810,-1.669466,0.459874,-1.244131,-1.793313,-0.506693,-0.938309,-0.215963,-1.717624,...,0.047339,0.134289,-0.232084,0.062456,0.341931,-0.105674,0.018577,0.060591,214.00,0.0
46396,42772,-0.094568,0.698891,1.600170,0.870068,-0.282404,1.375583,-0.963293,-1.268682,0.214792,...,1.428888,-0.601754,-0.260675,-0.816538,1.166240,-0.152007,0.233001,0.188659,4.99,0.0
54986,46718,-1.477450,1.439126,0.574047,-0.774514,-0.593818,-0.528083,-0.142391,1.042754,-0.215130,...,-0.122839,-0.460750,-0.003347,-0.006993,-0.139343,0.309154,0.147412,0.098248,4.00,0.0

In [14]:
new_df['Class'].value_counts()

Class
0.0    211
1.0    211
Name: count, dtype: int64